### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished when ActiveRecord isn't required in a project

### ISSUE THREAD

**Issue by dks17** [Netflix/fast_jsonapi#121]
I use mongoid v6.4 and rails v5.2.0.rc1 with no ActiveRecord.
config/application.rb
```ruby
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
# require "active_record/railtie"
# require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
# require "action_view/railtie"
require "action_cable/engine"
# require "sprockets/railtie"
# require "rails/test_unit/railtie"
```
The error raises while tests are passing:
```console
     ActiveRecord::ConnectionNotEstablished:
       No connection pool with 'primary' found.
```
I think the problem in [there](https://github.com/Netflix/fast_jsonapi/blob/7e59446717b0018f46c0d73a59e915acc15930b6/lib/extensions/has_one.rb#L3).

**Update1:**
Gemfile
```ruby
gem 'fast_jsonapi', github: 'Netflix/fast_jsonapi', branch: 'dev'
```
**Update2:**
I have no activerecord gem in Gemfile. But have activerecord dependencies in Gemfile.lock:
```
  rails (5.2.0.rc1)
      actioncable (= 5.2.0.rc1)
      actionmailer (= 5.2.0.rc1)
      actionpack (= 5.2.0.rc1)
      actionview (= 5.2.0.rc1)
      activejob (= 5.2.0.rc1)
      activemodel (= 5.2.0.rc1)
      activerecord (= 5.2.0.rc1)
```

**Comment by gsaks123** [comment]
This may already be fixed on the dev branch:
[https://github.com/Netflix/fast_jsonapi/blob/dev/lib/extensions/has_one.rb](https://github.com/Netflix/fast_jsonapi/blob/dev/lib/extensions/has_one.rb)

**Comment by dks17** [comment]
@gsaks123 I use `dev` branch of the gem. Please see updated  top comment.

**Comment by tscolari** [comment]
Replaying to @shishirmk from #124:
I can confirm that the problem I found in #124 was resolved by the `dev` version of the gem.
But because I was just spiking replacing AMS with this gem, unfortunately I'm not sure if there were any regressions :(

**Comment by shishirmk** [comment]
if this is no more an issue I would like to close this @dks17 can you confirm that this is fixed with the latest version of the gem?

**Comment by dks17** [comment]
@shishirmk the error still present.
I created a new test rails application and pushed it on [dks17/fast_jsonapi_mongoid](https://github.com/dks17/fast_jsonapi_mongoid) with last `fast_jsonapi` gem. Please see `readme` where are steps to reproducing the issue. Now anyone can see for themselves that the error still present.

**Comment by Cakirucho** [comment]
+1, i have the same issue using MongoID trying to run `tests`.

**Comment by dks17** [comment]
@Cakirucho, clone `master` branch and pull #123. Or override it manually in your local gem folder.

**Comment by shishirmk** [comment]
This issue should be fixed now as #123 is merged to dev. It will go out in the next version of the gem

**Comment by shishirmk** [comment]
This should be released in version 1.2 of the gem
